### PR TITLE
[TASK] Generate crowdin compatible XLF output

### PR DESCRIPTION
**Pull request by liayn**

### CODE REVIEW

**Comment by liayn** [comment]
See also: https://github.com/TYPO3-Initiatives/crowdin/issues/28

**Review by georgringer — CHANGES_REQUESTED** [review]
isn't the prefix `EXT:` missing @liayn ?

**Comment by liayn** [comment]
could be, but I would argue that it does not matter for those files, does it?
Those are not shared publicly usually and for my own, I know which file I'm dealing with, right?

**Comment by georgringer** [comment]
I still would prefer because those ext could also be part of a private repo at crowdin and I would use that format in docs

**Pull request closed without merging**
